name: formler
version: 0.0.4
author: Yulian Kuncheff <yulian@kuncheff.com>
description: A form parsing library. Multi-part, with files, and x-www-urlencoded.
homepage: https://github.com/Daegalus/formler
dependencies:
  logging: any
  unittest: any