name: formler
version: 0.1.1
author: Yulian Kuncheff <yulian@kuncheff.com>
description: A form parsing library. Multi-part, with files, and x-www-urlencoded.
homepage: https://github.com/Daegalus/formler
environment:
  sdk: ">=1.0.0 <2.0.0"
dependencies:
  crypto: ">=0.9.1 <0.10.0"
  logging: ">=0.9.3 <0.12.0"
dev_dependencies:
  unittest: ">=0.9.3 <0.12.0"
